name: Minify
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Job for Minify-JS
      - name: Minify
        uses: jossydevers/minify-js@v1.0.1
        with:
          directory: 'src/dnsclient.js' # (OPTIONAL)
          output: 'src/' # (OPTIONAL)
          
      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'minifyed'
          branch: ${{ github.ref }}
