name: Minify
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Minify
        uses: jossydevers/minify-js@v1.0.1
        with:
          directory: 'src/dnsclient.js'
          output: 'src/'
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'minifyed'
          branch: ${{ github.ref }}
